version: "3.9"
services:
  multi_modal_reaction_generation:
    env_file:
      - pyannote.env
    image: multi_modal_reaction_generation
    container_name: mr-gen
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    shm_size: "64gb"
    environment:
      - PYTHONPATH=/opt/ml
    ports:
      - 10028:10028
    volumes:
      - ./:/home/MultimodalReactionGeneration
      - ./docker/.ssh:/root/.ssh
    entrypoint: sh docker-entry.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    stdin_open: true
    tty: true
