version: "3.9"
services:
  multi_modal_reaction_generation:
    image: multi_modal_reaction_generation
    container_name: mr-gen
    build:
      context: .
      dockerfile: ./Dockerfile
    shm_size: "32gb"
    environment:
      - PYTHONPATH=/opt/ml
    ports:
      - 10028:10028
    volumes:
      # - /mnt/t4:/mnt/t4
      # - /home/mikawa/empath/intern:/home/mikawa/empath/intern
      - ./:/home/MultimodalReactionGeneration
    command: bash -c "bash entrypoint.sh && /bin/bash"
    entrypoint: sh docker-entry.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    stdin_open: true
    tty: true
